services:
  jenkins:
    build: .
    ports:
      - "8081:8080"
      - "50000:50000"
      - "4200:4200"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /run/docker.sock:/var/run/docker.sock
      - /home/halabbood/e-commerce-platform:/var/jenkins_home/workspace/ecommerce-pipeline
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    user: "1000:991"
    restart: unless-stopped

volumes:
  jenkins_home:
